version: '3.8'

services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql

  wordpress:
    image: wordpress:php7.4-apache
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      # See ./wordpress/wp-config.php
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    # We need to allow apache to write to the wordpress directory, otherwise we can't install plugins
    command: ["/bin/bash", "-c", "chown -R www-data:www-data /var/www/html && apache2-foreground"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
